/**
 * 对话详情-评论表单-权限控制
 *
 * A/B/..... - 当前状态
 *
 * Qc/cs/...... - 角色名称
 *
 * operation - 操作下拉框
 * ruleBig - 规则大类下拉框
 * ruleSmall - 规则小类目下拉框
 * input - 内容输入区
 * submit - 提交按钮
 * reviews - 评论历史列表
 *
 * [1,1]
 * - 第一个代表是否可见 1/0
 * - 第二个代表是否可以操作 1/0
 */
export const controlPermission = {
    A: {
        QC: {
            operation: [1, 1],
            ruleBig: [1, 1],
            ruleSmall: [1, 1],
            input: [1, 1],
            submit: [1, 1],
            reviews: [1],
        },
        Qcadmin: {
            operation: [1, 1],
            ruleBig: [1, 1],
            ruleSmall: [1, 1],
            input: [1, 1],
            submit: [1, 1],
            reviews: [1],
        },
        CS: {
            operation: [1, 1],
            ruleBig: [1, 0],
            ruleSmall: [1, 0],
            input: [1, 1],
            submit: [1, 1],
            reviews: [0],
        },
        Csleader: {
            operation: [1, 1],
            ruleBig: [1, 0],
            ruleSmall: [1, 0],
            input: [1, 1],
            submit: [1, 1],
            reviews: [0],
        },
    },
    B: {
        QC: {
            operation: [1, 0],
            ruleBig: [1, 0],
            ruleSmall: [1, 0],
            input: [1, 0],
            submit: [1, 0],
            reviews: [1],
        },
        Qcadmin: {
            operation: [1, 1],
            ruleBig: [1, 1],
            ruleSmall: [1, 1],
            input: [1, 1],
            submit: [1, 1],
            reviews: [1],
        },
        CS: {
            operation: [1, 0],
            ruleBig: [0, 0],
            ruleSmall: [0, 0],
            input: [1, 0],
            submit: [1, 0],
            reviews: [0],
        },
        Csleader: {
            operation: [1, 0],
            ruleBig: [0, 0],
            ruleSmall: [0, 0],
            input: [1, 0],
            submit: [1, 0],
            reviews: [0],
        },
    },
    C: {
        QC: {
            operation: [1, 1],
            ruleBig: [1, 1],
            ruleSmall: [1, 1],
            input: [1, 1],
            submit: [1, 1],
            reviews: [1],
        },
        Qcadmin: {
            operation: [1, 1],
            ruleBig: [1, 1],
            ruleSmall: [1, 1],
            input: [1, 1],
            submit: [1, 1],
            reviews: [1],
        },
        CS: {
            operation: [1, 0],
            ruleBig: [0, 0],
            ruleSmall: [0, 0],
            input: [1, 0],
            submit: [1, 0],
            reviews: [0],
        },
        Csleader: {
            operation: [1, 0],
            ruleBig: [0, 0],
            ruleSmall: [0, 0],
            input: [1, 0],
            submit: [1, 0],
            reviews: [0],
        },
    },
    D: {
        QC: {
            operation: [1, 0],
            ruleBig: [1, 0],
            ruleSmall: [1, 0],
            input: [1, 0],
            submit: [1, 0],
            reviews: [1],
        },
        Qcadmin: {
            operation: [1, 0],
            ruleBig: [1, 0],
            ruleSmall: [1, 0],
            input: [1, 0],
            submit: [1, 0],
            reviews: [1],
        },
        CS: {
            operation: [1, 1],
            ruleBig: [0, 0],
            ruleSmall: [0, 0],
            input: [1, 1],
            submit: [1, 1],
            reviews: [1],
        },
        Csleader: {
            operation: [1, 1],
            ruleBig: [0, 0],
            ruleSmall: [0, 0],
            input: [1, 1],
            submit: [1, 1],
            reviews: [1],
        },
    },
    E: {
        QC: {
            operation: [1, 0],
            ruleBig: [1, 0],
            ruleSmall: [1, 0],
            input: [1, 0],
            submit: [1, 0],
            reviews: [1],
        },
        Qcadmin: {
            operation: [1, 0],
            ruleBig: [1, 0],
            ruleSmall: [1, 0],
            input: [1, 0],
            submit: [1, 0],
            reviews: [1],
        },
        CS: {
            operation: [1, 0],
            ruleBig: [0, 0],
            ruleSmall: [0, 0],
            input: [1, 0],
            submit: [1, 0],
            reviews: [1],
        },
        Csleader: {
            operation: [1, 1],
            ruleBig: [0, 0],
            ruleSmall: [0, 0],
            input: [1, 1],
            submit: [1, 1],
            reviews: [1],
        },
    },
    F: {
        QC: {
            operation: [1, 1],
            ruleBig: [1, 1],
            ruleSmall: [1, 1],
            input: [1, 1],
            submit: [1, 1],
            reviews: [1],
        },
        Qcadmin: {
            operation: [1, 1],
            ruleBig: [1, 1],
            ruleSmall: [1, 1],
            input: [1, 1],
            submit: [1, 1],
            reviews: [1],
        },
        CS: {
            operation: [1, 0],
            ruleBig: [0, 0],
            ruleSmall: [0, 0],
            input: [1, 0],
            submit: [1, 0],
            reviews: [1],
        },
        Csleader: {
            operation: [1, 0],
            ruleBig: [0, 0],
            ruleSmall: [0, 0],
            input: [1, 0],
            submit: [1, 0],
            reviews: [1],
        },
    },
    G: {
        QC: {
            operation: [1, 1],
            ruleBig: [1, 0],
            ruleSmall: [1, 0],
            input: [1, 1],
            submit: [1, 1],
            reviews: [1],
        },
        Qcadmin: {
            operation: [1, 1],
            ruleBig: [1, 0],
            ruleSmall: [1, 0],
            input: [1, 1],
            submit: [1, 1],
            reviews: [1],
        },
        CS: {
            operation: [1, 0],
            ruleBig: [0, 0],
            ruleSmall: [0, 0],
            input: [1, 0],
            submit: [1, 0],
            reviews: [1],
        },
        Csleader: {
            operation: [1, 0],
            ruleBig: [0, 0],
            ruleSmall: [0, 0],
            input: [1, 0],
            submit: [1, 0],
            reviews: [1],
        },
    },
    H: {
        QC: {
            operation: [1, 1],
            ruleBig: [1, 0],
            ruleSmall: [1, 0],
            input: [1, 1],
            submit: [1, 1],
            reviews: [1],
        },
        Qcadmin: {
            operation: [1, 1],
            ruleBig: [1, 0],
            ruleSmall: [1, 0],
            input: [1, 1],
            submit: [1, 1],
            reviews: [1],
        },
        CS: {
            operation: [1, 0],
            ruleBig: [0, 0],
            ruleSmall: [0, 0],
            input: [1, 0],
            submit: [1, 0],
            reviews: [1],
        },
        Csleader: {
            operation: [1, 0],
            ruleBig: [0, 0],
            ruleSmall: [0, 0],
            input: [1, 0],
            submit: [1, 0],
            reviews: [1],
        },
    },
    I: {
        QC: {
            operation: [1, 1],
            ruleBig: [1, 1],
            ruleSmall: [1, 1],
            input: [1, 1],
            submit: [1, 1],
            reviews: [1],
        },
        Qcadmin: {
            operation: [1, 1],
            ruleBig: [1, 1],
            ruleSmall: [1, 1],
            input: [1, 1],
            submit: [1, 1],
            reviews: [1],
        },
        CS: {
            operation: [1, 0],
            ruleBig: [0, 0],
            ruleSmall: [0, 0],
            input: [1, 0],
            submit: [1, 0],
            reviews: [1],
        },
        Csleader: {
            operation: [1, 0],
            ruleBig: [0, 0],
            ruleSmall: [0, 0],
            input: [1, 0],
            submit: [1, 0],
            reviews: [1],
        },
    },
    J: {
        QC: {
            operation: [1, 0],
            ruleBig: [1, 0],
            ruleSmall: [1, 0],
            input: [1, 0],
            submit: [1, 0],
            reviews: [1],
        },
        Qcadmin: {
            operation: [1, 0],
            ruleBig: [1, 0],
            ruleSmall: [1, 0],
            input: [1, 0],
            submit: [1, 0],
            reviews: [1],
        },
        CS: {
            operation: [1, 0],
            ruleBig: [0, 0],
            ruleSmall: [0, 0],
            input: [1, 0],
            submit: [1, 0],
            reviews: [1],
        },
        Csleader: {
            operation: [1, 0],
            ruleBig: [0, 0],
            ruleSmall: [0, 0],
            input: [1, 0],
            submit: [1, 0],
            reviews: [1],
        },
    },
    K: {
        QC: {
            operation: [1, 1],
            ruleBig: [1, 1],
            ruleSmall: [1, 1],
            input: [1, 1],
            submit: [1, 1],
            reviews: [1],
        },
        Qcadmin: {
            operation: [1, 1],
            ruleBig: [1, 1],
            ruleSmall: [1, 1],
            input: [1, 1],
            submit: [1, 1],
            reviews: [1],
        },
        CS: {
            operation: [1, 0],
            ruleBig: [0, 0],
            ruleSmall: [0, 0],
            input: [1, 0],
            submit: [1, 0],
            reviews: [1],
        },
        Csleader: {
            operation: [1, 0],
            ruleBig: [0, 0],
            ruleSmall: [0, 0],
            input: [1, 0],
            submit: [1, 0],
            reviews: [1],
        },
    },
    L: {
        QC: {
            operation: [1, 0],
            ruleBig: [1, 0],
            ruleSmall: [1, 0],
            input: [1, 0],
            submit: [1, 0],
            reviews: [1],
        },
        Qcadmin: {
            operation: [1, 0],
            ruleBig: [1, 0],
            ruleSmall: [1, 0],
            input: [1, 0],
            submit: [1, 0],
            reviews: [1],
        },
        CS: {
            operation: [1, 1],
            ruleBig: [1, 0],
            ruleSmall: [1, 0],
            input: [1, 1],
            submit: [1, 1],
            reviews: [1],
        },
        Csleader: {
            operation: [1, 1],
            ruleBig: [1, 1],
            ruleSmall: [1, 1],
            input: [1, 1],
            submit: [1, 1],
            reviews: [1],
        },
    },
    M: {
        QC: {
            operation: [1, 1],
            ruleBig: [1, 1],
            ruleSmall: [1, 1],
            input: [1, 1],
            submit: [1, 1],
            reviews: [1],
        },
        Qcadmin: {
            operation: [1, 1],
            ruleBig: [1, 1],
            ruleSmall: [1, 1],
            input: [1, 1],
            submit: [1, 1],
            reviews: [1],
        },
        CS: {
            operation: [1, 0],
            ruleBig: [0, 0],
            ruleSmall: [0, 0],
            input: [1, 0],
            submit: [1, 0],
            reviews: [1],
        },
        Csleader: {
            operation: [1, 0],
            ruleBig: [0, 0],
            ruleSmall: [0, 0],
            input: [1, 0],
            submit: [1, 0],
            reviews: [1],
        },
    },
    N: {
        QC: {
            operation: [1, 1],
            ruleBig: [1, 1],
            ruleSmall: [1, 1],
            input: [1, 1],
            submit: [1, 1],
            reviews: [1],
        },
        Qcadmin: {
            operation: [1, 1],
            ruleBig: [1, 1],
            ruleSmall: [1, 1],
            input: [1, 1],
            submit: [1, 1],
            reviews: [1],
        },
        CS: {
            operation: [1, 0],
            ruleBig: [0, 0],
            ruleSmall: [0, 0],
            input: [1, 0],
            submit: [1, 0],
            reviews: [1],
        },
        Csleader: {
            operation: [1, 0],
            ruleBig: [0, 0],
            ruleSmall: [0, 0],
            input: [1, 0],
            submit: [1, 0],
            reviews: [1],
        },
    },
    O: {
        QC: {
            operation: [1, 1],
            ruleBig: [1, 1],
            ruleSmall: [1, 1],
            input: [1, 1],
            submit: [1, 1],
            reviews: [1],
        },
        Qcadmin: {
            operation: [1, 1],
            ruleBig: [1, 1],
            ruleSmall: [1, 1],
            input: [1, 1],
            submit: [1, 1],
            reviews: [1],
        },
        CS: {
            operation: [1, 0],
            ruleBig: [0, 0],
            ruleSmall: [0, 0],
            input: [1, 0],
            submit: [1, 0],
            reviews: [1],
        },
        Csleader: {
            operation: [1, 0],
            ruleBig: [0, 0],
            ruleSmall: [0, 0],
            input: [1, 0],
            submit: [1, 0],
            reviews: [1],
        },
    },
    P: {
        QC: {
            operation: [1, 0],
            ruleBig: [1, 0],
            ruleSmall: [1, 0],
            input: [1, 0],
            submit: [1, 0],
            reviews: [1],
        },
        Qcadmin: {
            operation: [1, 0],
            ruleBig: [1, 0],
            ruleSmall: [1, 0],
            input: [1, 0],
            submit: [1, 0],
            reviews: [1],
        },
        CS: {
            operation: [1, 0],
            ruleBig: [0, 0],
            ruleSmall: [0, 0],
            input: [1, 0],
            submit: [1, 0],
            reviews: [0],
        },
        Csleader: {
            operation: [1, 0],
            ruleBig: [0, 0],
            ruleSmall: [0, 0],
            input: [1, 0],
            submit: [1, 0],
            reviews: [0],
        },
    },
};

/**
 * 操作下拉框，需要根据当前的状态和角色显示不同的下拉内容
 */
export const operationSelectionContent = {
    A1: [
        { key: '对话无误', value: 9 },
        { key: '质检复核', value: 15 },
    ],
    A2: [
        { key: '推荐对话', value: 11 },
    ],
    B: [
        { key: '质检修正', value: 3 },
        { key: '网站查看', value: 4 },
        { key: '对话退回', value: 16 },
    ],
    C: [{ key: '上级复核', value: 2 }],
    D: [{ key: '客服申诉', value: 5 }],
    E: [
        { key: '同意申诉', value: 6 },
        { key: '申诉失败', value: 7 },
    ],
    F: [
        { key: '申诉修正', value: 8 },
        { key: '申诉失败', value: 7 },
    ],
    G: [{ key: '对话完结', value: 10 }],
    H: [{ key: '对话完结', value: 10 }],
    I: [{ key: '质检复核', value: 15 }],
    J: [],
    K: [{ key: '对话驳回', value: 12 },
        { key: '质检复核', value: 15 }],
    L: [{ key: '推荐申诉', value: 13 }],
    M: [
        { key: '推荐失败', value: 14 },
        { key: '质检复核', value: 15 }
    ],
    N: [{ key: '对话完结', value: 10 }],
    O: [
        { key: '上级复核', value: 2 },
    ],
    P: []
};

// http://10.71.12.73:8080/#/qualitycheck/dialog-detail?id=f40c9b7c08ac4e8bb76abd4998b63672
